[project]
name = "sticker-importer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-genai>=1.59.0",
    "pillow>=12.1.0",
    "python-dotenv>=1.2.1",
    "rich>=14.2.0",
    "typer>=0.21.1",
    "imagehash>=4.3.1",
    "numpy>=1.26.0",
]
